version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 573687461965.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t betterkanban-api:latest .
      - docker tag betterkanban-api:latest 573687461965.dkr.ecr.us-east-1.amazonaws.com/betterkanban-api:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 573687461965.dkr.ecr.us-east-1.amazonaws.com/betterkanban-api:latest
      - printf '[{"name":"betterkanban-api","imageUri":"573687461965.dkr.ecr.us-east-1.amazonaws.com/betterkanban-api:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
