version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - npm install
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 573687461965.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - npm run build
      - echo Building the Docker image...
      - docker build -t betterkanban-api .
      - docker tag betterkanban-api:latest 573687461965.dkr.ecr.us-east-1.amazonaws.com/betterkanban-api:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 573687461965.dkr.ecr.us-east-1.amazonaws.com/betterkanban-api:latest
      - printf '[{"name":"betterkanban-api","imageUri":"%s"}]' 573687461965.dkr.ecr.us-east-1.amazonaws.com/betterkanban-api:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
