version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - npm install
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f1z9f8i1
  build:
    commands:
      - npm run build
      - echo Building the Docker image...
      - docker build -t betterkanban-dev .
      - docker tag betterkanban-dev:latest public.ecr.aws/f1z9f8i1/betterkanban-dev:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push public.ecr.aws/f1z9f8i1/betterkanban-dev:latest
      - printf '[{"name":"betterkanban-dev","imageUri":"public.ecr.aws/f1z9f8i1/betterkanban-dev:latest"}]' > imagedefinitions.json

  artifcats:
    files: imagedefinitions.json