-- AlterTable
ALTER TABLE `Customer` ADD COLUMN `AccountStatus` VARCHAR(191) NULL,
    ADD COLUMN `Source` VARCHAR(191) NULL,
    ADD COLUMN `jobTitle` VARCHAR(191) NULL,
    ADD COLUMN `phoneNumber` VARCHAR(191) NULL;
